# Github Action Built Image
FROM milysun/ldaca-text-analytics-tools:e76b0ccb1760
# Submodule hashes and commit URLs for this build (generated at 2025-09-21T08:02:15Z UTC, parent repo e76b0ccb17605d882cc4b33f046c2d365d2111da)
# (Debug) Listing submodule pointers from git ls-tree:
# ldaca_web_app: af94bca41412 https://github.com/Australian-Text-Analytics-Platform/ldaca_web_app/tree/af94bca41412
# docframe: ccacbbbdabcd https://github.com/Australian-Text-Analytics-Platform/docframe/tree/ccacbbbdabcd
