# Github Action Built Image.
FROM milysun/ldaca-text-analytics-tools:ffedee8eac64
# Submodule hashes and commit URLs for this build (generated at 2025-09-28T04:58:10Z UTC, parent repo ffedee8eac64695190322628c1e6edf1a57dab72)
# (Debug) Listing submodule pointers from git ls-tree:
# ldaca_web_app: ce5562785adc https://github.com/Australian-Text-Analytics-Platform/ldaca_web_app/tree/ce5562785adc
# docframe: 29537d162aaf https://github.com/Australian-Text-Analytics-Platform/docframe/tree/29537d162aaf
# Submodule hashes and commit URLs for this build (generated at 2025-09-26T01:00:48Z UTC, parent repo 8d35567d8036582e2ca954b512cc3daa6a165360)
# (Debug) Listing submodule pointers from git ls-tree:
# ldaca_web_app: 7cfa1a130ae0 https://github.com/Australian-Text-Analytics-Platform/ldaca_web_app/tree/7cfa1a130ae0
# docframe: ccacbbbdabcd https://github.com/Australian-Text-Analytics-Platform/docframe/tree/ccacbbbdabcd
