# Github Action Built Image.
FROM milysun/ldaca-text-analytics-tools:67c88a6afeaa
# Submodule hashes and commit URLs for this build (generated at 2025-10-15T02:05:45Z UTC, parent repo 67c88a6afeaa6331520fe957d0f4e863c1462d21)
# (Debug) Listing submodule pointers from git ls-tree:
# ldaca_web_app: 937d611ab6eb https://github.com/Australian-Text-Analytics-Platform/ldaca_web_app/tree/937d611ab6eb
# docframe: 29537d162aaf https://github.com/Australian-Text-Analytics-Platform/docframe/tree/29537d162aaf
